In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df_exercise = pd.read_csv('dataset/gym_members_exercise_tracking.csv')
df_met = pd.read_csv('dataset/met.csv')

In [36]:
df_exercise.head()

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.20
1,46,Female,74.9,1.53,179,151,66,1.30,883.0,HIIT,33.9,2.1,4,2,32.00
2,32,Female,68.1,1.66,167,122,54,1.11,677.0,Cardio,33.4,2.3,4,2,24.71
3,25,Male,53.2,1.70,190,164,56,0.59,532.0,Strength,28.8,2.1,3,1,18.41
4,38,Male,46.1,1.79,188,158,68,0.64,556.0,Strength,29.2,2.8,3,1,14.39

In [37]:
df_met.head()

,Unnamed: 0,Actvitiy,Code,MET,Description
0,0,Bicycling,1004,16.0,"Bicycling, mountain, competitive racing"
1,1,Bicycling,1008,8.5,"Bicycling, BMX"
2,2,Bicycling,1009,8.5,"Bicycling, mountain, general"
3,3,Bicycling,1010,4.0,"Bicycling, <10 mph, leisure, to work or for pl..."
4,4,Bicycling,1011,6.8,"Bicycling, to/from work, self selected pace"

### Data Preprocessing

In [38]:
df_met.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1125 non-null   int64
 1   Actvitiy     1125 non-null   object
 2   Code         1125 non-null   int64
 3   MET          1125 non-null   float64
 4   Description  1125 non-null   object
dtypes: float64(1), int64(2), object(2)
memory usage: 44.1+ KB

In [39]:
def set_workout_type(met):
    if met < 4.0:
        return 'Yoga'
    elif 4.0 <= met <= 6.0:
        return 'Strength'
    elif 6.0 < met <= 10.0:
        return 'Cardio'
    else:
        return 'HIIT'

df_met['Workout_Type'] = df_met['MET'].apply(set_workout_type)

df_met.head()

,Unnamed: 0,Actvitiy,Code,MET,Description,Workout_Type
0,0,Bicycling,1004,16.0,"Bicycling, mountain, competitive racing",HIIT
1,1,Bicycling,1008,8.5,"Bicycling, BMX",Cardio
2,2,Bicycling,1009,8.5,"Bicycling, mountain, general",Cardio
3,3,Bicycling,1010,4.0,"Bicycling, <10 mph, leisure, to work or for pl...",Strength
4,4,Bicycling,1011,6.8,"Bicycling, to/from work, self selected pace",Cardio

In [40]:
df_merged = pd.merge(df_exercise, df_met, on='Workout_Type', how='inner', suffixes=('_ex','_met'))
df_merged.head()

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI,Unnamed: 0,Actvitiy,Code,MET,Description
0,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.2,10,Bicycling,1018,3.5,"Bicycling, leisure 5.5 mph"
1,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.2,24,Bicycling,1210,3.5,"Bicycling, stationary, 25-30 watts, very light..."
2,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.2,38,Bicycling,1262,2.3,"Bicycling, eccentric only, 100 to 149 W"
3,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.2,53,Conditioning Exercise,2022,3.8,"Calisthenics (e.g., pushups, sit ups, pull-ups..."
4,56,Male,88.3,1.71,180,157,60,1.69,1313.0,Yoga,12.6,3.5,4,3,30.2,54,Conditioning Exercise,2024,2.8,"Calisthenics (e.g., curl ups, abdominal crunch..."